### ISSUE TITLE
Where is the new userscript?

### ISSUE THREAD

**Issue by EliusHHimel** [PlaceNL/Userscript#1]

**Comment by NoahvdAa** [comment]
The majority of the new userscript code has now been pushed, or at least the part we can create before r/place starts. This year we're taking a slightly different approach than last year. Last year we shoved the entirety of the userscript into one file, whereas we now use webpack to keep the codebase a bit more organised.

A downloadable and installable userscript will be available soon:tm: (as in, today or tomorrow), but keep in mind that it won't do anything yet as we don't know what the actual requests to r/place will look like.
