### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Vandit2405** [PlaceNL/Userscript#4]
Hey, can you please let me know how to configure this autoplacer for another artwork? I need to help a smaller community defend their work. Please let me know what to edit and how to start that edit (Fork i guess? uhh), just explain in english please. Thank you so much :)

**Comment by NoahvdAa** [comment]
Our autoplacers are all commanded by [Chief](https://github.com/PlaceNL/Chief). You don't need to make changes to it if you just want to use it for your community, so you can just configure it and start it up. I recommend using Docker, but you can also just run it as a Node.JS application if you prefer.
You can configure Chief via environment variables, see [here](https://github.com/PlaceNL/Chief/blob/master/src/constants.js) for the full list. The important and required ones are `BASE_URL`, `DISCORD_CLIENT_ID`, `DISCORD_CLIENT_SECRET`, `DISCORD_SERVER_ID`, `DISCORD_ROLE_ID`, and `POSTGRES_CONNECTION_URI` (chief needs a Postgresql database).

Then, you need to fork the Userscript (this repo) and change the following things:
- Websocket endpoint in src/constants.js
  https://github.com/PlaceNL/Userscript/blob/6b2631e098010207143294012fbac74ee8f61c62/src/constants.js#L1
- Change the updateURL, downloadURL and script_location to your Github repository in the autoupdater script:
  https://github.com/PlaceNL/Userscript/blob/6b2631e098010207143294012fbac74ee8f61c62/placenl-userscript-autoupdater.user.js#L11-L18
- Change the updateURL, and the downloadURL to your Github repository in the userscript header:
  https://github.com/PlaceNL/Userscript/blob/6b2631e098010207143294012fbac74ee8f61c62/src/USERSCRIPT_HEADER.txt#L11-L12
- Update the links in the READMe to your Github repository.
- (Optional) Add your own language, see the [lang folder](https://github.com/PlaceNL/Userscript/tree/6b2631e098010207143294012fbac74ee8f61c62/src/lang) for an example (nl). 

If you have any further questions feel free to ask here or in the #place-development channel of [our Discord](https://discord.gg/placenl).
